# Exported from Render on 2025-07-30T15:02:27Z
services:
- type: web
  name: n8n
  runtime: node
  repo: https://github.com/dingschoolz/n8n
  plan: free
  envVars:
  - key: NODE_VERSION
    sync: false
  region: oregon
  buildCommand: pnpm install --frozen-lockfile; pnpm run build
  startCommand: pnpm run start
  autoDeployTrigger: commit
version: "1"
